CREATE DATABASE IF NOT EXISTS event_management;
USE event_management;

DROP TABLE users;
DROP TABLE email_otp;

CREATE TABLE IF NOT EXISTS users (
    u_id INT AUTO_INCREMENT PRIMARY KEY,
    u_first_name VARCHAR(50) NOT NULL,
    u_last_name VARCHAR(50) NOT NULL,
    u_email VARCHAR(100) NOT NULL UNIQUE,
    u_password VARCHAR(255) NOT NULL,
    u_is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_otp (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    otp VARCHAR(10) NOT NULL,
    expires_at DATETIME NOT NULL
);
